name: patient_manager_app
description: A cross-platform (mobile + desktop) Flutter app to store patient data locally with printing.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  printing: ^5.9.0
  pdf: ^3.10.1
  path_provider: ^2.0.15
  intl: ^0.18.0
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  shared_preferences: ^2.5.3
flutter:
  uses-material-design: true
  assets:
    - assets/images/logos.jpg
    - assets/images/signature.png
    - assets/images/signature.jpeg
